apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: chaoshub
  name: chaoshub
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chaoshub
    spec:
      containers:
      - image: chaostoolkit/chaoshub:0.1.2
        imagePullPolicy: Never
        name: chaoshub
        ports:
        - containerPort: 8080
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
