version: '3.2'

services:
#  docker-base-image:
#    build: docker-base-image/
#    image: docker-base-image

#  chaostoolkit:
#    build: chaostoolkit-base/
#    tty: true

  chaoshub:
    image: chaostoolkit/chaoshub:0.1.2
    ports:
    - "8888:8080"
    tty: true

  api-gateway:
    image: api-gateway
    ports:
    - "8080:8080"

  fashion:
    image: bestseller-fashion
    ports:
    - "8082"
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
  toys:
    image: bestseller-toys
    ports:
    - "8081"
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr

  hot-deals:
    image: hot-deals
    ports:
    - "8083:8083"

  eureka-server:
    image: eureka-server
    ports:
    - "8761:8761"