apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: docker-base-image
  name: docker-base-image
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: docker-base-image
    spec:
      containers:
      - image: docker-base-image
        name: docker-base-image
        resources: {}
      restartPolicy: Always
status: {}
