spring:
  data:
    rest:
      base-path:
  application:
    name: api-gateway
rest:
  endpoint:
    fashion: "http://fashion.shopping-demo:8082/fashion/bestseller"
    toys: "http://toys-bestseller/toys/bestseller/"
    hotdeals: "http://hotdeals/hotdeals"
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
