
spring:
  data:
    rest:
      base-path:

rest:
  endpoint:
    fashion: "http://fashion-bestseller/fashion/bestseller"
    toys: "http://localhost:8081/toys/bestseller/"
    hotdeals: "http://localhost:8083/hotdeals"
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
