rest:
  endpoint:
    fashion: "http://fashion.shoppingdemo:8082/fashion/bestseller"
    toys: "http://toys.shoppingdemo:8081/toys/bestseller"
    hotdeals: "http://hot-deals.shoppingdemo:8083/hotdeals"