server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  metrics:
    enabled: true
  command:
    fashion:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200
    fashionLoadBalanced:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 400
    hotdeals:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200
    hotdealsLoadBalanced:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 400
    toys:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200
    toysLoadBalanced:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 400
rest:
  endpoint:
    fashion: "http://localhost:8082/fashion/bestseller"
    toys: "http://localhost:8081/toys/bestseller"
    hotdeals: "http://localhost:8083/hotdeals"