apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shoppingdemo
  name: chaostoolkit-pod
  labels:
    app: chaostoolkit
    type: chaos-engineering-tool
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chaostoolkit
    spec:
      containers:
      - image: docker.io/mrbwilms/chaostoolkit:latest
        name: chaostoolkit
        resources: {}
        tty: true
      restartPolicy: Always
  selector:
    matchLabels:
      app: chaostoolkit