apiVersion: v1
kind: Service
metadata:
  namespace: shoppingdemo
  name: chaostoolkit
  labels:
    app: shoppingdemo
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    app: chaostoolkit
status:
  loadBalancer: {}