apiVersion: v1
kind: Service
metadata:
  namespace: shopping-demo
  name: chaostoolkit
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    shopping.demo.service: chaostoolkit
status:
  loadBalancer: {}