apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: shopping-demo
  name: api-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        shopping.demo.service: gateway
    spec:
      containers:
      - image: docker.io/mrbwilms/gateway:latest
        name: gateway
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
