apiVersion: v1
kind: Service
metadata:
  namespace: shopping-demo
  name: api-gateway
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    shopping.demo.service: api-gateway
status:
  loadBalancer: {}