apiVersion: v1
kind: Service
metadata:
  namespace: shopping-demo
  name: toys
spec:
  ports:
  - name: "http"
    port: 8081
    targetPort: 8081
  selector:
    shopping.demo.service: toys
status:
  loadBalancer: {}
