apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shopping-demo
  name: hot-deals
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        shopping.demo.service: hot-deals
    spec:
      containers:
      - image: docker.io/mrbwilms/hot-deals:latest
        name: hotdeals
        ports:
        - containerPort: 8083
        resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      shopping.demo.service: hot-deals
