server:
  port: 8083
spring:
  profiles:
    active: chaos-monkey
  application:
    name: hotdeals
  zipkin:
    base-url: http://jaegertracing:9411
    sender:
      type: web

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: chaosmonkey
chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
      service: false
    assaults:
      latency-active: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/